dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 0.10.0
    - name: rabbitmq
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 0.7.6
