apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudlaunchServer.fullname" . }}-init-scripts
  labels:
    app: {{ template "cloudlaunchServer.name" . }}
    chart: {{ template "cloudlaunchServer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  create_superuser.py: |
{{ $.Files.Get "scripts/create_superuser.py" | indent 4 }}
  0_init_container.sh: |
{{ $.Files.Get "scripts/0_init_container.sh" | indent 4 }}
{{- if .Values.extra_init_scripts }}
{{- with .Values.extra_init_scripts }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}