apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloudlaunchServer.fullname" . }}
  labels:
    app: {{ template "cloudlaunchServer.name" . }}
    chart: {{ template "cloudlaunchServer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ template "cloudlaunchServer.name" . }}
    release: {{ .Release.Name }}
    # Also match component so that all matching pods aren't included in this service
    component: django
