dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.8.7
    - name: rabbitmq-ha
      repository: https://charts.helm.sh/stable
      version: 1.38.2
      alias: rabbitmq
