dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.1.2
    - name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.22.2
      alias: rabbitmq
