---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cloudlaunch-server.fullname" . }}-celery
  labels:
    app: {{ template "cloudlaunch-server.name" . }}
    chart: {{ template "cloudlaunch-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: celery
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cloudlaunch-server.name" . }}
      release: {{ .Release.Name }}
      component: celery
  template:
    metadata:
      labels:
        app: {{ template "cloudlaunch-server.name" . }}
        release: {{ .Release.Name }}
        component: celery
    spec:
      # Give 30 mins for celery worker to finish
      terminationGracePeriodSeconds: 1800
      containers:
        - name: {{ .Values.container_name | default .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
          args: ["-E", "-A", {{ .Values.celery_app_name | default "cloudlaunchserver" | quote }},
                 "-l", "info", "--beat", "worker"]
          lifecycle:
            preStop:
              exec:
                # Trigger a graceful shutdown of the worker by sending SIGTERM and waiting for process exit
                command: ["/bin/sh", "-ce", "pkill celery; while pkill -0 celery; do sleep 5; done"]
          readinessProbe:
            exec:
              command: ["bash",
                        "-c",
                        "celery inspect ping -A {{ .Values.celery_app_name | default "cloudlaunchserver" }} -d celery@$HOSTNAME"]
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["bash",
                        "-c",
                        "celery inspect ping -A {{ .Values.celery_app_name | default "cloudlaunchserver" }} -d celery@$HOSTNAME"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
          {{- include "cloudlaunch-server.envvars" . }}
{{- range $key, $val := .Values.extra_env }}
{{- if $val }}
            - name: {{ $key | upper }}
              value: "{{ tpl $val $ }}"
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
