---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cloudlaunch.fullname" . }}-celery
  labels:
    app: {{ template "cloudlaunch.name" . }}
    chart: {{ template "cloudlaunch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cloudlaunch.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cloudlaunch.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
          args: ["-E", "-A", "cloudlaunchserver", "-l", "info", "--beat", "worker"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: CELERY_BROKER_URL
              value: amqp://{{ .Values.rabbitmq.rabbitmqUsername }}:{{ .Values.rabbitmq.rabbitmqPassword }}@{{ template "rabbitmq.fullname" . }}:5672/
            - name: DJANGO_SETTINGS_MODULE
              value: cloudlaunchserver.settings_prod
            - name: CLOUDLAUNCH_DB_ENGINE
              value: postgresql_psycopg2
            - name: CLOUDLAUNCH_DB_NAME
              value: {{ default "cloudlaunch" .Values.postgresql.postgresDatabase | quote }}
            - name: CLOUDLAUNCH_DB_USER
              value: {{ default "cloudlaunch" .Values.postgresql.postgresUser | quote }}
            - name: CLOUDLAUNCH_DB_HOST
              value: {{ template "postgresql.fullname" . }}
            - name: CLOUDLAUNCH_DB_PORT
              value: {{ default 5432 .Values.postgresql.service.port | quote }}
            - name: CLOUDLAUNCH_DB_PASSWORD
              value: {{ .Values.postgresql.postgresPassword | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
