apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloudlaunch-server.fullname" . }}
  labels:
    app: {{ template "cloudlaunch-server.name" . }}
    chart: {{ template "cloudlaunch-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ template "cloudlaunch-server.name" . }}
    release: {{ .Release.Name }}
    # Also match component so that all matching pods aren't included in this service
    component: django
