apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cloudlaunch-server.fullname" . }}-db-migrate-job
  labels:
    app: {{ template "cloudlaunch-server.name" . }}
    chart: {{ template "cloudlaunch-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.container_name | default .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['python', '{{ .Values.django_dir }}/manage.py', 'migrate']
          env:
          {{- include "cloudlaunch-server.envvars" . }}
          {{- include "cloudlaunch-server.extra_envvars" .Values.extra_env }}
      restartPolicy: Never
