---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cloudlaunch-server.fullname" . }}
  labels:
    app: {{ template "cloudlaunch-server.name" . }}
    chart: {{ template "cloudlaunch-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cloudlaunch-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cloudlaunch-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Values.container_name | default .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '{{ .Values.django_dir }}/scripts/init_container.sh']
          env:
            - name: DJANGO_ADMIN_PASSWORD
              value: {{ .Values.admin_password | quote }}
{{- /*
  Trick to globally disable certificate verification as OIDC will fail due to unverified certificate
  https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module?rq=1
*/}}
            - name: CURL_CA_BUNDLE
              value: ""
          {{- include "cloudlaunch-server.envvars" . }}
{{- range $key, $val := .Values.extra_env }}
{{- if $val }}
            - name: {{ $key | upper }}
              value: "{{ tpl $val $ }}"
{{- end }}
{{- end }}
          volumeMounts:
            - name: initial-data
              mountPath: /app/initial_data
              readOnly: true
      volumes:
        - name: initial-data
          configMap:
            name: {{ template "cloudlaunch-server.fullname" . }}-initial-data
      containers:
        - name: {{ .Values.container_name | default .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          env:
            - name: HELMSMAN_AUTO_DEPLOY
              value: "true"
{{- /*
  Trick to globally disable certificate verification as OIDC will fail due to unverified certificate
  https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module?rq=1
*/}}
            - name: CURL_CA_BUNDLE
              value: ""
          {{- include "cloudlaunch-server.envvars" . }}
{{- range $key, $val := .Values.extra_env }}
{{- if $val }}
            - name: {{ $key | upper }}
              value: "{{ tpl $val $ }}"
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
